namespace: security

progressDeadlineSeconds: 15
replicas: 1

maxSurge: "25%"
maxUnavailable: 25%

image: "docker.io/pglombardo/pwpush-ephemeral"
imagePullPolicy: "Always"

requestMemory: "256Mi"
requestCpu: 1

limitsMemory: "512Mi"
limitsCpu: 1.5
        
terminationMessagePath: /dev/termination-log
terminationMessagePolicy: FallbackToLogsOnError

env:
  - name: TZ
    value: "America/Sao_Paulo"
  - name: PWP__DEFAULT_LOCALE
    value: "en"
  - name: PWP__LOG_LEVEL
    value: "warn"
      
dnsPolicy: ClusterFirst
restartPolicy: Always
schedulerName: default-scheduler
securityContext: {}
terminationGracePeriodSeconds: 30
